version: "3.7"

services:
    httpdump:
        image: dockette/mockbin
        ports:
            - 8000:8000
        environment:
            - MOCKBIN_REDIS=redis://redis:6379

    redis:
        image: redis:7-alpine
        ports:
            - 6379:6379
